spring:
  datasource:
    url: jdbc:mysql://localhost:3306/marketinall?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: true
    defer-datasource-initialization: true

    servlet:
      multipart:
        max-file-size: 512MB
        max-request-size: 512MB
        location: d:\\temp\\spring_uploaded_files

  profiles:
    include: oauth
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 309419092088-tr9hmdai3qpej7vvjubppj0qjm3bbvkm.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

logging:
  level:
    org.hibernate.SQL: debug
#    org.hibernate.type: trace

file:
  dir: C:/study/file/

jwt:
  issuer: saab35@naver.com
  secret_key: and0LXRlc3QtYWxqamFiYWVnaS1qd3QtdGVzdC1hbGpqYWJhZWdpLWp3dC10ZXN0LWFsamphYmFlZ2ktand0LXRlc3QtYWxqamFiYWVnaS1qd3QtdGVzdC1hbGpqYWJhZWdpLWp3dC10ZXN0LWFsamphYmFlZ2ktand0LXRlc3QtYWxqamFiYWVnaS1qd3QtdGVzdC1hbGpqYWJhZWdp


